// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDLu5AfpbeSee69uyAG3YgfG3r0wjphQ',
    appId: '1:1081737259963:web:5beeab33b2b5942fa0729e',
    messagingSenderId: '1081737259963',
    projectId: 'bq-quiz-lab-74d5c',
    authDomain: 'bq-quiz-lab-74d5c.firebaseapp.com',
    storageBucket: 'bq-quiz-lab-74d5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaJaWog6VO8yh1xUHgZ5AXh1G01Z2OvE',
    appId: '1:1081737259963:android:b43c69a5345b9a31a0729e',
    messagingSenderId: '1081737259963',
    projectId: 'bq-quiz-lab-74d5c',
    storageBucket: 'bq-quiz-lab-74d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLLPFM9FY8F-elYSIvE6kKZDPxPRUX3Es',
    appId: '1:1081737259963:ios:97c655250f672767a0729e',
    messagingSenderId: '1081737259963',
    projectId: 'bq-quiz-lab-74d5c',
    storageBucket: 'bq-quiz-lab-74d5c.firebasestorage.app',
    iosBundleId: 'com.example.bqQuizLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLLPFM9FY8F-elYSIvE6kKZDPxPRUX3Es',
    appId: '1:1081737259963:ios:97c655250f672767a0729e',
    messagingSenderId: '1081737259963',
    projectId: 'bq-quiz-lab-74d5c',
    storageBucket: 'bq-quiz-lab-74d5c.firebasestorage.app',
    iosBundleId: 'com.example.bqQuizLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpDLu5AfpbeSee69uyAG3YgfG3r0wjphQ',
    appId: '1:1081737259963:web:e022e2a27e7fd171a0729e',
    messagingSenderId: '1081737259963',
    projectId: 'bq-quiz-lab-74d5c',
    authDomain: 'bq-quiz-lab-74d5c.firebaseapp.com',
    storageBucket: 'bq-quiz-lab-74d5c.firebasestorage.app',
  );
}
